### ISSUE TITLE
Given a sha256, how can one find the user's pubkey?

### ISSUE THREAD

**Issue by ibz** [hzrd149/blossom#11]
I would expect there to be a way to get the user's pubkey from a sha256, but I can't find it...

**Comment by ibz** [comment]
OK, I'll answer it myself, after looking at `blossom-server-sdk`... I understood. Of course there is no way. Because the same blob can belong to more than one user.

**Comment by hzrd149** [comment]
yes a single sha256 could belong to multiple users. a good example of this would be the bitcoin white paper which is `b1674191a88ec5cdd733e4240a81803105dc412d6c6708d53ab94fc248f4f553 `

As for finding users servers, that can be done with the `10063` event kind in https://github.com/hzrd149/blossom/blob/master/Nostr.md
