### ISSUE TITLE
Could we further modularize the protocol?

### ISSUE THREAD

**Issue by danieldaquino** [hzrd149/blossom#14]
I like the concepts used in the Blossom protocol, and it is similar to a NIP I was working on (https://github.com/nostr-protocol/nips/pull/1098/files)

I was considering turning that NIP draft into its own protocol (Blobstr), but I believe it might be better to implement some of those ideas into the Blossom protocol instead to avoid duplicating efforts.

However, the concern I have about the Blossom protocol is that [BUD-01](https://github.com/hzrd149/blossom/blob/master/buds/bud-01.md) is a bit monolithic and constraints the possible use cases. For example, it prevents the following:
- Read-only Blossom servers (e.g. Say someone just wants to host a curated set of files, or share files from a local directory, as some form of archive)
- NIP-98 authorization (e.g. If users want to purposefully limit the upload/download to specific servers for better privacy, for example in the case of operating within a local network)
- Likely other use cases

In general, content-addressable storage can serve a big variety of use cases, so I believe it might be a good idea to reduce BUD-01 into something smaller and add-on the other features/requirements into BUD-02, BUD-03, etc, to serve specific use-cases, that way the protocol can serve more use-cases. If BUD-01 is too restrictive and mandatory, it cannot be used for a broad set of use cases and will encourage those to use different protocols.

Is this something you'd be interested in? I could come up with some drafts if interested.

**Comment by danieldaquino** [comment]
Thank you @hzrd149 for putting that together! Yes, that's what I had in mind.

I still need to wrap my mind around the GET authentication/authorization mechanism, but I can open a separate ticket if I have concerns about that

**Comment by melvincarvalho** [comment]
You might want to have a look at : https://nosdav.com/spec/

**Comment by melvincarvalho** [comment]
And: https://datatracker.ietf.org/doc/html/rfc6920

**Comment by melvincarvalho** [comment]
I wrote this mail to the w3c community group:

https://lists.w3.org/Archives/Public/public-nostr/2024Aug/0000.html

**Comment by danieldaquino** [comment]
Thank you @melvincarvalho for sharing these links. I bookmarked them and I will keep them in mind for future projects.

Thank you @hzrd149 for https://github.com/hzrd149/blossom/pull/15. That separation into BUD-01 and BUD-02 covers the concern I posed in this Github issue. I believe this issue can be closed, but please feel free to reopen if you disagree
