### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by dergigi** [hzrd149/blossom#5]
Add a LICENSE file to indicate what license the project is published under.

More info & helpful links:
- [GitHub: Licensing a repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)
- [Pick a License, Any License](https://blog.codinghorror.com/pick-a-license-any-license/)
- [Choose an open-source license](https://choosealicense.com/)
- [GNU License List](https://www.gnu.org/licenses/license-list.html)

**Comment by hzrd149** [comment]
Thanks for the reminder, added the "Unlicense" or "public domain" license to the project
