### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by fishcakeday** [hzrd149/blossom#6]
Why create yet another (and not even standardized) method to upload media? Are you planning to submit this as a PR for the NIPs repo? Was this well-thought-out? Was there a need? This just further creats fragmentation on already highly fragmented protocol. Did you think of scalability, reliability, resiliency of this approach? Costs? Implementation? Do you plan for it to be used only by sole individuals? Larger hosts? What is the point?

**Comment by hzrd149** [comment]
to answer your questions in order
experimentation, no, kind of, yes, yes, yes, a little, yes, no, yes, everyone, yes, content addressable files

**Comment by ibz** [comment]
Indeed, this feels a lot like NIP-96. I was also thinking, what is the point? I guess we'll have to wait and see which one gains more traction...

**Comment by ibz** [comment]
> NIP-96 does content addressable content already

It does not, actually.
